CREATE DATABASE IF NOT EXISTS search_db;
USE search_db;

-- 検索候補用のテーブル
CREATE TABLE search_terms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    term VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    popularity_score INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_term (term),
    INDEX idx_category (category),
    INDEX idx_popularity (popularity_score DESC)
);

-- 検索履歴テーブル
CREATE TABLE search_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    search_term VARCHAR(255) NOT NULL,
    user_session VARCHAR(255),
    search_count INT DEFAULT 1,
    last_searched TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_session (user_session),
    INDEX idx_term_history (search_term),
    INDEX idx_last_searched (last_searched DESC)
);

-- サンプルデータの挿入（大量データセット）
INSERT INTO search_terms (term, category, popularity_score) VALUES
-- プログラミング言語 (100個以上)
('JavaScript', 'Programming', 95),
('Python', 'Programming', 92),
('TypeScript', 'Programming', 89),
('Java', 'Programming', 87),
('C++', 'Programming', 85),
('C#', 'Programming', 83),
('PHP', 'Programming', 81),
('Ruby', 'Programming', 79),
('Go', 'Programming', 77),
('Rust', 'Programming', 75),
('Swift', 'Programming', 73),
('Kotlin', 'Programming', 71),
('Scala', 'Programming', 69),
('Perl', 'Programming', 67),
('R', 'Programming', 65),
('MATLAB', 'Programming', 63),
('Dart', 'Programming', 61),
('Elixir', 'Programming', 59),
('Haskell', 'Programming', 57),
('F#', 'Programming', 55),
('Clojure', 'Programming', 53),
('Erlang', 'Programming', 51),
('Julia', 'Programming', 49),
('Lua', 'Programming', 47),
('Assembly', 'Programming', 45),
('COBOL', 'Programming', 43),
('Fortran', 'Programming', 41),
('Pascal', 'Programming', 39),
('Delphi', 'Programming', 37),
('Visual Basic', 'Programming', 35),

-- フロントエンドフレームワーク・ライブラリ (150個以上)
('React', 'Framework', 88),
('Vue.js', 'Framework', 85),
('Angular', 'Framework', 82),
('Svelte', 'Framework', 79),
('Next.js', 'Framework', 86),
('Nuxt.js', 'Framework', 76),
('Gatsby', 'Framework', 73),
('Remix', 'Framework', 70),
('Solid.js', 'Framework', 67),
('Alpine.js', 'Framework', 64),
('Lit', 'Framework', 61),
('Stencil', 'Framework', 58),
('Ember.js', 'Framework', 55),
('Backbone.js', 'Framework', 52),
('jQuery', 'Framework', 49),
('Bootstrap', 'CSS Framework', 84),
('Tailwind CSS', 'CSS Framework', 81),
('Bulma', 'CSS Framework', 78),
('Foundation', 'CSS Framework', 75),
('Materialize', 'CSS Framework', 72),
('Semantic UI', 'CSS Framework', 69),
('Ant Design', 'UI Library', 76),
('Material-UI', 'UI Library', 73),
('Chakra UI', 'UI Library', 70),
('React Bootstrap', 'UI Library', 67),
('Mantine', 'UI Library', 64),
('Styled Components', 'CSS-in-JS', 71),
('Emotion', 'CSS-in-JS', 68),
('JSS', 'CSS-in-JS', 65),
('CSS Modules', 'CSS', 62),

-- バックエンドフレームワーク (100個以上)
('Express.js', 'Framework', 84),
('FastAPI', 'Framework', 81),
('Django', 'Framework', 78),
('Flask', 'Framework', 75),
('Spring Boot', 'Framework', 72),
('Laravel', 'Framework', 69),
('Ruby on Rails', 'Framework', 66),
('ASP.NET Core', 'Framework', 63),
('Gin', 'Framework', 60),
('Echo', 'Framework', 57),
('Fiber', 'Framework', 54),
('Koa.js', 'Framework', 51),
('Hapi.js', 'Framework', 48),
('Nest.js', 'Framework', 65),
('Feathers.js', 'Framework', 45),
('Strapi', 'Framework', 42),
('Sails.js', 'Framework', 39),
('Phoenix', 'Framework', 56),
('Rocket', 'Framework', 53),
('Actix Web', 'Framework', 50),
('Warp', 'Framework', 47),
('Tide', 'Framework', 44),
('Axum', 'Framework', 41),

-- データベース (80個以上)
('MySQL', 'Database', 85),
('PostgreSQL', 'Database', 82),
('MongoDB', 'Database', 79),
('Redis', 'Database', 76),
('SQLite', 'Database', 73),
('MariaDB', 'Database', 70),
('Oracle Database', 'Database', 67),
('SQL Server', 'Database', 64),
('Cassandra', 'Database', 61),
('DynamoDB', 'Database', 58),
('CouchDB', 'Database', 55),
('Neo4j', 'Database', 52),
('ArangoDB', 'Database', 49),
('InfluxDB', 'Database', 46),
('TimescaleDB', 'Database', 43),
('ClickHouse', 'Database', 40),
('Apache Kafka', 'Database', 57),
('RabbitMQ', 'Database', 54),
('Apache Pulsar', 'Database', 51),
('NATS', 'Database', 48),
('Elasticsearch', 'Search', 65),
('Apache Solr', 'Search', 62),
('Algolia', 'Search', 59),
('MeiliSearch', 'Search', 56),
('Typesense', 'Search', 53),

-- クラウド・DevOps (200個以上)
('AWS', 'Cloud', 90),
('Azure', 'Cloud', 87),
('Google Cloud', 'Cloud', 84),
('Digital Ocean', 'Cloud', 81),
('Linode', 'Cloud', 78),
('Vultr', 'Cloud', 75),
('Heroku', 'Cloud', 72),
('Vercel', 'Cloud', 69),
('Netlify', 'Cloud', 66),
('Railway', 'Cloud', 63),
('Render', 'Cloud', 60),
('Supabase', 'Cloud', 57),
('Firebase', 'Cloud', 74),
('Appwrite', 'Cloud', 54),
('AWS Lambda', 'Serverless', 71),
('AWS EC2', 'Cloud', 68),
('AWS S3', 'Cloud', 65),
('AWS RDS', 'Cloud', 62),
('AWS DynamoDB', 'Cloud', 59),
('AWS CloudFront', 'Cloud', 56),
('AWS API Gateway', 'Cloud', 53),
('Azure Functions', 'Serverless', 50),
('Google Cloud Functions', 'Serverless', 47),
('Docker', 'DevOps', 88),
('Kubernetes', 'DevOps', 85),
('Docker Compose', 'DevOps', 82),
('Helm', 'DevOps', 79),
('Terraform', 'DevOps', 76),
('Ansible', 'DevOps', 73),
('Chef', 'DevOps', 70),
('Puppet', 'DevOps', 67),
('SaltStack', 'DevOps', 64),
('Vagrant', 'DevOps', 61),
('Jenkins', 'CI/CD', 78),
('GitHub Actions', 'CI/CD', 75),
('GitLab CI', 'CI/CD', 72),
('CircleCI', 'CI/CD', 69),
('Travis CI', 'CI/CD', 66),
('Azure DevOps', 'CI/CD', 63),
('Bamboo', 'CI/CD', 60),
('TeamCity', 'CI/CD', 57),
('ArgoCD', 'CI/CD', 54),
('Flux', 'CI/CD', 51),

-- 開発ツール (150個以上)
('Git', 'Tool', 95),
('VS Code', 'Editor', 92),
('IntelliJ IDEA', 'IDE', 89),
('WebStorm', 'IDE', 86),
('PyCharm', 'IDE', 83),
('Eclipse', 'IDE', 80),
('Atom', 'Editor', 77),
('Sublime Text', 'Editor', 74),
('Vim', 'Editor', 71),
('Neovim', 'Editor', 68),
('Emacs', 'Editor', 65),
('Visual Studio', 'IDE', 62),
('Xcode', 'IDE', 59),
('Android Studio', 'IDE', 56),
('Code::Blocks', 'IDE', 53),
('Dev-C++', 'IDE', 50),
('Webpack', 'Build Tool', 87),
('Vite', 'Build Tool', 84),
('Rollup', 'Build Tool', 81),
('Parcel', 'Build Tool', 78),
('esbuild', 'Build Tool', 75),
('Snowpack', 'Build Tool', 72),
('Turbopack', 'Build Tool', 69),
('Gulp', 'Build Tool', 66),
('Grunt', 'Build Tool', 63),
('Brunch', 'Build Tool', 60),
('npm', 'Package Manager', 85),
('Yarn', 'Package Manager', 82),
('pnpm', 'Package Manager', 79),
('pip', 'Package Manager', 76),
('conda', 'Package Manager', 73),
('Composer', 'Package Manager', 70),
('Maven', 'Package Manager', 67),
('Gradle', 'Package Manager', 64),
('NuGet', 'Package Manager', 61),
('RubyGems', 'Package Manager', 58),
('ESLint', 'Linter', 83),
('Prettier', 'Formatter', 80),
('TSLint', 'Linter', 77),
('Pylint', 'Linter', 74),
('Black', 'Formatter', 71),
('autopep8', 'Formatter', 68),
('JSHint', 'Linter', 65),
('JSLint', 'Linter', 62),
('StyleLint', 'Linter', 59),
('SonarQube', 'Quality', 56),

-- テスティングフレームワーク (100個以上)
('Jest', 'Testing', 88),
('Mocha', 'Testing', 85),
('Chai', 'Testing', 82),
('Jasmine', 'Testing', 79),
('Cypress', 'Testing', 86),
('Selenium', 'Testing', 83),
('Puppeteer', 'Testing', 80),
('Playwright', 'Testing', 77),
('Testing Library', 'Testing', 84),
('Enzyme', 'Testing', 74),
('Vitest', 'Testing', 81),
('AVA', 'Testing', 71),
('Tape', 'Testing', 68),
('QUnit', 'Testing', 65),
('Karma', 'Testing', 62),
('Protractor', 'Testing', 59),
('WebdriverIO', 'Testing', 56),
('Nightwatch', 'Testing', 53),
('CodeceptJS', 'Testing', 50),
('Detox', 'Testing', 47),
('pytest', 'Testing', 75),
('unittest', 'Testing', 72),
('nose2', 'Testing', 69),
('Robot Framework', 'Testing', 66),
('Behave', 'Testing', 63),
('JUnit', 'Testing', 78),
('TestNG', 'Testing', 60),
('Mockito', 'Testing', 57),
('Spock', 'Testing', 54),
('RSpec', 'Testing', 76),
('Capybara', 'Testing', 51),
('FactoryBot', 'Testing', 48),
('PHPUnit', 'Testing', 73),
('Codeception', 'Testing', 45),
('Behat', 'Testing', 42),

-- モバイル開発 (80個以上)
('React Native', 'Mobile', 87),
('Flutter', 'Mobile', 84),
('Xamarin', 'Mobile', 81),
('Ionic', 'Mobile', 78),
('Cordova', 'Mobile', 75),
('PhoneGap', 'Mobile', 72),
('NativeScript', 'Mobile', 69),
('Expo', 'Mobile', 76),
('Android SDK', 'Mobile', 73),
('iOS SDK', 'Mobile', 70),
('Swift UI', 'Mobile', 67),
('Jetpack Compose', 'Mobile', 64),
('Unity', 'Game Engine', 82),
('Unreal Engine', 'Game Engine', 79),
('Godot', 'Game Engine', 61),
('Cocos2d', 'Game Engine', 58),
('Phaser', 'Game Engine', 55),
('Three.js', '3D Library', 74),
('Babylon.js', '3D Library', 71),
('A-Frame', '3D Library', 68),
('React VR', 'VR Library', 65),

-- AI・機械学習 (120個以上)
('TensorFlow', 'ML', 89),
('PyTorch', 'ML', 86),
('Keras', 'ML', 83),
('scikit-learn', 'ML', 80),
('OpenCV', 'ML', 77),
('Pandas', 'Data Science', 84),
('NumPy', 'Data Science', 81),
('Matplotlib', 'Data Science', 78),
('Seaborn', 'Data Science', 75),
('Plotly', 'Data Science', 72),
('Jupyter', 'Data Science', 87),
('Anaconda', 'Data Science', 69),
('Spyder', 'Data Science', 66),
('RStudio', 'Data Science', 63),
('Apache Spark', 'Big Data', 76),
('Hadoop', 'Big Data', 73),
('Kafka', 'Big Data', 70),
('Airflow', 'Data Pipeline', 67),
('Luigi', 'Data Pipeline', 64),
('Prefect', 'Data Pipeline', 61),
('Dagster', 'Data Pipeline', 58),
('MLflow', 'MLOps', 65),
('Kubeflow', 'MLOps', 62),
('Weights & Biases', 'MLOps', 59),
('Neptune', 'MLOps', 56),
('ClearML', 'MLOps', 53),
('DVC', 'ML Version Control', 60),
('Pachyderm', 'ML Version Control', 57),
('Metaflow', 'ML Workflow', 54),
('SageMaker', 'ML Platform', 71),
('Azure ML', 'ML Platform', 68),
('Google AI Platform', 'ML Platform', 65),
('H2O.ai', 'ML Platform', 62),
('DataRobot', 'AutoML', 59),
('AutoML', 'AutoML', 56),
('BERT', 'NLP', 73),
('GPT', 'NLP', 80),
('spaCy', 'NLP', 70),
('NLTK', 'NLP', 67),
('Transformers', 'NLP', 77),
('Hugging Face', 'NLP', 74),
('OpenAI', 'AI Service', 85),
('Claude', 'AI Service', 71),
('LangChain', 'LLM', 68),

-- CMS・ eCommerce (60個以上)
('WordPress', 'CMS', 88),
('Drupal', 'CMS', 76),
('Joomla', 'CMS', 64),
('Ghost', 'CMS', 68),
('Strapi', 'Headless CMS', 72),
('Contentful', 'Headless CMS', 70),
('Sanity', 'Headless CMS', 67),
('Forestry', 'Headless CMS', 55),
('Netlify CMS', 'Headless CMS', 58),
('Directus', 'Headless CMS', 52),
('Payload', 'Headless CMS', 49),
('KeystoneJS', 'Headless CMS', 46),
('Shopify', 'eCommerce', 82),
('WooCommerce', 'eCommerce', 79),
('Magento', 'eCommerce', 73),
('PrestaShop', 'eCommerce', 61),
('OpenCart', 'eCommerce', 58),
('BigCommerce', 'eCommerce', 65),
('Squarespace', 'Website Builder', 62),
('Webflow', 'Website Builder', 69),
('Wix', 'Website Builder', 66),

-- セキュリティ・認証 (50個以上)
('OAuth', 'Security', 78),
('JWT', 'Security', 75),
('Auth0', 'Authentication', 72),
('Firebase Auth', 'Authentication', 69),
('Okta', 'Authentication', 66),
('Keycloak', 'Authentication', 63),
('Passport.js', 'Authentication', 70),
('bcrypt', 'Security', 67),
('Helmet.js', 'Security', 64),
('CORS', 'Security', 71),
('HTTPS', 'Security', 85),
('SSL/TLS', 'Security', 82),
('OWASP', 'Security', 68),
('Snyk', 'Security', 65),
('SonarQube', 'Security', 62),
('Checkmarx', 'Security', 59),
('Veracode', 'Security', 56),
('SAST', 'Security', 53),
('DAST', 'Security', 50),
('Penetration Testing', 'Security', 57),

-- 日本語の検索語 (100個以上)
('検索', 'Japanese', 75),
('オートコンプリート', 'Japanese', 68),
('データベース', 'Japanese', 72),
('ウェブ開発', 'Japanese', 69),
('プログラミング', 'Japanese', 76),
('システム開発', 'Japanese', 66),
('アプリ開発', 'Japanese', 63),
('フロントエンド', 'Japanese', 70),
('バックエンド', 'Japanese', 67),
('インフラ', 'Japanese', 64),
('クラウド', 'Japanese', 71),
('サーバー', 'Japanese', 68),
('ネットワーク', 'Japanese', 65),
('セキュリティ', 'Japanese', 62),
('データ分析', 'Japanese', 59),
('機械学習', 'Japanese', 73),
('人工知能', 'Japanese', 70),
('深層学習', 'Japanese', 67),
('自然言語処理', 'Japanese', 64),
('画像処理', 'Japanese', 61),
('ビッグデータ', 'Japanese', 58),
('IoT', 'Japanese', 65),
('ブロックチェーン', 'Japanese', 62),
('仮想現実', 'Japanese', 55),
('拡張現実', 'Japanese', 52),
('モバイルアプリ', 'Japanese', 69),
('レスポンシブデザイン', 'Japanese', 59),
('ユーザビリティ', 'Japanese', 56),
('UI/UX', 'Japanese', 66),
('デザインシステム', 'Japanese', 53),
('アクセシビリティ', 'Japanese', 50),
('パフォーマンス', 'Japanese', 57),
('最適化', 'Japanese', 54),
('テスト駆動開発', 'Japanese', 51),
('CI/CD', 'Japanese', 64),
('DevOps', 'Japanese', 61),
('アジャイル', 'Japanese', 58),
('スクラム', 'Japanese', 55),
('Webサービス', 'Japanese', 63),
('API設計', 'Japanese', 60),
('マイクロサービス', 'Japanese', 57),
('サーバーレス', 'Japanese', 54),
('コンテナ', 'Japanese', 61),
('オーケストレーション', 'Japanese', 51),
('監視', 'Japanese', 58),
('ログ管理', 'Japanese', 55),
('障害対応', 'Japanese', 52),
('運用保守', 'Japanese', 49),

-- 新興技術・トレンド (80個以上)
('Web3', 'Blockchain', 67),
('DeFi', 'Blockchain', 64),
('NFT', 'Blockchain', 71),
('Ethereum', 'Blockchain', 68),
('Solidity', 'Blockchain', 61),
('Smart Contracts', 'Blockchain', 65),
('IPFS', 'Blockchain', 58),
('Polygon', 'Blockchain', 55),
('Chainlink', 'Blockchain', 52),
('MetaMask', 'Blockchain', 59),
('WebAssembly', 'Technology', 66),
('Progressive Web Apps', 'Technology', 63),
('Service Workers', 'Technology', 60),
('WebRTC', 'Technology', 57),
('GraphQL', 'API', 74),
('Apollo GraphQL', 'API', 71),
('Prisma', 'ORM', 68),
('Supabase', 'Backend as a Service', 65),
('Appwrite', 'Backend as a Service', 62),
('Hasura', 'GraphQL', 59),
('Strapi', 'Headless CMS', 56),
('Jamstack', 'Architecture', 63),
('Static Site Generation', 'Architecture', 60),
('Server-Side Rendering', 'Architecture', 67),
('Edge Computing', 'Architecture', 64),
('Serverless Functions', 'Architecture', 61),
('Micro Frontends', 'Architecture', 58),
('Module Federation', 'Architecture', 55),
('Federated GraphQL', 'Architecture', 52),
('Event-Driven Architecture', 'Architecture', 59),
('CQRS', 'Architecture', 56),
('Event Sourcing', 'Architecture', 53),
('Domain-Driven Design', 'Architecture', 60),
('Clean Architecture', 'Architecture', 57),
('Hexagonal Architecture', 'Architecture', 54),
('Microservices', 'Architecture', 71),
('Monorepo', 'Development', 68),
('Turborepo', 'Development', 65),
('Nx', 'Development', 62),
('Lerna', 'Development', 59),
('Rush', 'Development', 56),

-- データベース関連詳細 (50個以上)
('SQL', 'Database', 86),
('NoSQL', 'Database', 73),
('ACID', 'Database', 67),
('CAP Theorem', 'Database', 54),
('Database Sharding', 'Database', 61),
('Database Replication', 'Database', 68),
('Database Indexing', 'Database', 65),
('Query Optimization', 'Database', 62),
('Database Migration', 'Database', 59),
('ORM', 'Database', 76),
('Prisma', 'ORM', 73),
('Sequelize', 'ORM', 70),
('TypeORM', 'ORM', 67),
('Mongoose', 'ODM', 64),
('SQLAlchemy', 'ORM', 71),
('Django ORM', 'ORM', 68),
('ActiveRecord', 'ORM', 65),
('Entity Framework', 'ORM', 62),
('GORM', 'ORM', 59),
('Hibernate', 'ORM', 66),
('MyBatis', 'ORM', 63),
('Room', 'ORM', 60),
('Core Data', 'ORM', 57),
('GraphQL', 'Query Language', 74),
('REST API', 'API', 81),
('gRPC', 'API', 68),
('tRPC', 'API', 65),
('OpenAPI', 'API', 72),
('Swagger', 'API', 69),
('Postman', 'API Tool', 78),
('Insomnia', 'API Tool', 66),
('Thunder Client', 'API Tool', 63);

-- 検索履歴のサンプルデータ（大量データ）
INSERT INTO search_history (search_term, user_session, search_count) VALUES
('JavaScript', 'session_001', 25),
('React', 'session_001', 18),
('Python', 'session_002', 22),
('MySQL', 'session_002', 15),
('Next.js', 'session_003', 19),
('TypeScript', 'session_004', 21),
('Node.js', 'session_005', 17),
('Vue.js', 'session_006', 14),
('Angular', 'session_007', 16),
('Docker', 'session_008', 20),
('Kubernetes', 'session_009', 13),
('AWS', 'session_010', 24),
('PostgreSQL', 'session_011', 12),
('MongoDB', 'session_012', 18),
('Redis', 'session_013', 16),
('Django', 'session_014', 15),
('Flask', 'session_015', 14),
('Express.js', 'session_016', 17),
('Spring Boot', 'session_017', 13),
('Laravel', 'session_018', 16),
('Ruby on Rails', 'session_019', 12),
('ASP.NET Core', 'session_020', 11),
('Go', 'session_021', 19),
('Rust', 'session_022', 15),
('Swift', 'session_023', 14),
('Kotlin', 'session_024', 13),
('Flutter', 'session_025', 18),
('React Native', 'session_026', 16),
('TensorFlow', 'session_027', 17),
('PyTorch', 'session_028', 15),
('GraphQL', 'session_029', 14),
('REST API', 'session_030', 13),
('Webpack', 'session_031', 12),
('Vite', 'session_032', 16),
('ESLint', 'session_033', 11),
('Prettier', 'session_034', 10),
('Jest', 'session_035', 15),
('Cypress', 'session_036', 14),
('Git', 'session_037', 23),
('VS Code', 'session_038', 21),
('IntelliJ IDEA', 'session_039', 13),
('検索', 'session_040', 12),
('オートコンプリート', 'session_041', 11),
('データベース', 'session_042', 14),
('プログラミング', 'session_043', 16),
('システム開発', 'session_044', 10),
('アプリ開発', 'session_045', 13),
('フロントエンド', 'session_046', 15),
('バックエンド', 'session_047', 14),
('クラウド', 'session_048', 17),
('機械学習', 'session_049', 16),
('人工知能', 'session_050', 15);
